const {createClient}=supabase;const db=createClient(window.AIMPACT_CONFIG.supabaseUrl,window.AIMPACT_CONFIG.supabaseKey);let tools=[];let selected=[];const $=id=>document.getElementById(id);
async function event(name,payload={}){try{await db.from("events").insert({event_name:name,payload,pathname:location.pathname})}catch(e){console.warn("event",e)}}
function normalize(t){return {...t,name:t.name||"Unnamed AI Tool",category:t.category||"Other",pricing:(t.pricing||"").toUpperCase(),description:t.description||"Verified AI tool.",url:t.official_url||"#"}}
function render(){const q=$("search").value.trim().toLowerCase(),cat=$("category").value,price=$("pricing").value;const list=tools.filter(t=>(!q||JSON.stringify(t).toLowerCase().includes(q))&&(!cat||t.category===cat)&&(!price||t.pricing.includes(price)));$("grid").innerHTML=list.map(t=>'<article class="card"><div><span class="tag">'+t.category+' · '+t.pricing+'</span><h3>'+escapeHtml(t.name)+'</h3><p>'+escapeHtml(t.description)+'</p></div><div class="actions"><button class="primary" onclick="detail(\''+t.id+'\')">VIEW</button><button onclick="toggleCompare(\''+t.id+'\')">COMPARE</button></div></article>').join("")||'<div class="loading">No verified tools match your search.</div>';updateCompare()}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
window.detail=async id=>{const t=tools.find(x=>x.id===id);if(!t)return;$("modalBody").innerHTML='<span class="tag">'+escapeHtml(t.category)+' · '+escapeHtml(t.pricing)+'</span><h2>'+escapeHtml(t.name)+'</h2><p>'+escapeHtml(t.description)+'</p><p><b>Verification:</b> '+escapeHtml(t.verification_status)+'</p><a class="primary" target="_blank" rel="noopener" href="'+escapeHtml(t.url)+'">VISIT OFFICIAL SITE →</a>';$("modal").classList.add("show");event("tool_view",{tool_id:t.id,name:t.name})}
window.toggleCompare=id=>{selected=selected.includes(id)?selected.filter(x=>x!==id):selected.length<3?[...selected,id]:selected;updateCompare();event("compare",{tool_ids:selected})}
function updateCompare(){const box=$("compareBox");if(!selected.length){box.innerHTML="<p>No tools selected.</p>";return}const ts=selected.map(id=>tools.find(t=>t.id===id)).filter(Boolean);box.innerHTML='<div class="compareRow">'+ts.map(t=>'<div class="compareItem"><b>'+escapeHtml(t.name)+'</b><p>'+escapeHtml(t.category)+'</p><p>'+escapeHtml(t.pricing)+'</p><p>'+escapeHtml(t.description)+'</p></div>').join("")+'</div>'}
async function init(){const {data,error}=await db.from("public_tools").select("*").eq("verification_status","VERIFIED").order("name");if(error){$("grid").innerHTML='<div class="loading">Production database connection error.</div>';console.error(error);return}tools=(data||[]).map(normalize);$("toolCount").textContent=tools.length;$("categoryCount").textContent=new Set(tools.map(t=>t.category)).size;$("freeCount").textContent=tools.filter(t=>/FREE|FREEMIUM/.test(t.pricing)).length;const cats=[...new Set(tools.map(t=>t.category))].sort();cats.forEach(c=>{const o=document.createElement("option");o.value=c;o.textContent=c;$("category").appendChild(o)});render();event("page_view")}
$("search").addEventListener("input",render);$("category").addEventListener("change",render);$("pricing").addEventListener("change",render);$("close").onclick=()=>$("modal").classList.remove("show");$("modal").onclick=e=>{if(e.target===$("modal"))$("modal").classList.remove("show")};init();