const config=window.AIMPACT_CONFIG||{};const supabase=supabaseClient();let session=null;let tenantId=null;
function supabaseClient(){if(!config.supabaseUrl||!config.supabaseAnonKey)throw new Error("SUPABASE_CONFIG_REQUIRED");return window.supabase.createClient(config.supabaseUrl,config.supabaseAnonKey)}
const $=s=>document.querySelector(s);function note(el,msg,state=""){el.textContent=msg;el.className="note "+state}
function unlock(){["companyCard","verificationCard"].forEach(id=>$( "#"+id).classList.remove("locked"))}
async function refresh(){const r=await supabase.auth.getSession();session=r.data.session||null;if(session)unlock();return session}
$("#signup").onclick=async()=>{const f=new FormData($("#authForm"));const r=await supabase.auth.signUp({email:String(f.get("email")).trim(),password:String(f.get("password"))});if(r.error)return note($("#authNote"),r.error.message,"error");note($("#authNote"),"Account created. Confirm email if required, then sign in.","ok")}
$("#signin").onclick=async()=>{const f=new FormData($("#authForm"));const r=await supabase.auth.signInWithPassword({email:String(f.get("email")).trim(),password:String(f.get("password"))});if(r.error)return note($("#authNote"),r.error.message,"error");session=r.data.session;unlock();note($("#authNote"),"Authenticated. Complete company registration.","ok")}
$("#companyForm").onsubmit=async e=>{e.preventDefault();if(!session)return note($("#companyNote"),"Sign in first.","error");const f=new FormData(e.currentTarget);const slug=String(f.get("slug")).trim();try{const r=await fetch("/.netlify/functions/tenant-bootstrap",{method:"POST",headers:{Authorization:"Bearer "+session.access_token,"Content-Type":"application/json"},body:JSON.stringify({name:String(f.get("legal_name")).trim(),slug})});const d=await r.json();if(!r.ok)throw new Error(d.code||"TENANT_CREATE_FAILED");tenantId=d.tenant_id;note($("#companyNote"),"Company workspace verified. Continue to business verification.","ok");$("#verificationCard").classList.remove("locked")}catch(err){note($("#companyNote"),err.message,"error")}}
$("#verificationForm").onsubmit=async e=>{e.preventDefault();if(!session||!tenantId)return note($("#verificationNote"),"Complete company registration first.","error");const f=new FormData(e.currentTarget);f.append("tenant_id",tenantId);const account=String(f.get("bank_account")).replace(/\\s+/g,"");f.set("bank_account",account);const r=await fetch("/.netlify/functions/business-onboarding",{method:"POST",headers:{Authorization:"Bearer "+session.access_token},body:f});const d=await r.json().catch(()=>({}));if(!r.ok)return note($("#verificationNote"),d.code||"SUBMISSION_FAILED","error");note($("#verificationNote"),"Business verification submitted securely. Your Customer App is ready for the next step.","ok");$("#nextCard").classList.remove("locked");$("#verificationForm").querySelector("button").disabled=true}
refresh().catch(err=>note($("#authNote"),err.message||"Unable to initialize authentication.","error"));
